### ISSUE TITLE
Wanted: Docker file + Docker Compose

### ISSUE THREAD

**Issue by Zorlin** [Lilypad-Tech/lilybot#2]
It's not how we're choosing to run it (yet) but it would be nice to have later.

**Comment by salmandotexe** [comment]
Hi @Zorlin, I had a brief look at the codebase when I was searching for open issues and I came across this haha. I have the changes locally, but cannot create an MR as I don't have write access to the repository. 

`remote: Permission to Lilypad-Tech/lilybot.git denied to salmandotexe.`

Could you allow MRs with review?

**Comment by AquiGorka** [comment]
@salmandotexe if you fork the repo, update your `main` branch locally and then push to your fork you can open a PR

**Comment by salmandotexe** [comment]
> @salmandotexe if you fork the repo, update your `main` branch locally and then push to your fork you can open a PR

Ah thanks! I've created one now. Please take a look: https://github.com/Lilypad-Tech/lilybot/pull/4
